version: '3'
services:
  adserver:
    build: 
      context: .
    restart: always
    depends_on:
      - postgresdb
    networks:
      - adserver-network
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
      - OXHUT_URL=${OXHUT_URL}
      - OXHUT_AUTH_SERVER_SIGNING_KEY=${OXHUT_AUTH_SERVER_SIGNING_KEY}
    ports:
      - "4000:3000"
  
  postgresdb:
    image: postgres:15.3-alpine
    restart: always
    volumes:
      - pg-data-vol:/var/lib/postgresql/data
    networks:
      - adserver-network
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

volumes:
  pg-data-vol:

networks:
  adserver-network:
    driver: bridge
    name: adserver-net